# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b002592ebc880f9421b9a4a27fbef63efddb71251e62ecb740cf98971843760863326afa46c6d8033fef197dfd5c9ad8d641080aa132cb26a12e5c72953f184e

test:
  secret_key_base: 89bc5a90ddbcc1a3e4e436e76e1db70e3596e5120835d7fb789e750db754218f6779cc83aeb636f7530488a31151e146b82e294a35588075db71c99b9936e90b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
